matchingPieces-base
kdrzewiecki101/mahjong2022 pull request #9
Opened 2022-05-31 16:30 UTC by RafalZmija

2022-05-31 22:16 UTC, n2oneProgrammer requested changes
Hi

2022-05-31 22:16 UTC, n2oneProgrammer commented on static/js/Game.js
> +                    //console.log("TOP MATERIAL PATH: " + topMaterialPath)
just remove it not comment

2022-05-31 22:16 UTC, n2oneProgrammer commented on static/js/Game.js
>                      // console.log(piece);
useless comment

2022-05-31 22:16 UTC, n2oneProgrammer commented on static/js/Game.js
>          // console.log(intersects.length)
useless

2022-05-31 22:16 UTC, n2oneProgrammer commented on static/js/Game.js
> +                    // console.log(intersects[0].object.id)
useless

2022-05-31 22:16 UTC, n2oneProgrammer commented on static/js/Game.js
> +                    //Znalezienie ostatnio klikniętego elementu po jego id i podmiana jego mesha jw
dont comment "useless code"

2022-05-31 22:16 UTC, n2oneProgrammer commented on static/js/Game.js
> +        console.log(lastClickedPieceImageObj)
debug

2022-05-31 22:16 UTC, n2oneProgrammer commented on static/js/Game.js
>          //console.log("render leci")
useless

2022-05-31 22:16 UTC, n2oneProgrammer commented on static/js/images.js
> +    //console.log(imagesLeft)
useless

2022-05-31 22:16 UTC, n2oneProgrammer commented on static/js/images.js
>      let XXXX = images
nice name of var

2022-05-31 22:16 UTC, n2oneProgrammer commented on static/js/images.js
>      let XXXX = images
say everything

2022-05-31 22:16 UTC, n2oneProgrammer commented on static/js/images.js
> +    //console.log(startingItemsArray)
useless

2022-05-31 22:16 UTC, n2oneProgrammer commented on static/js/Game.js
>  let zmiennaX = 4.6
nice var, I know everything

2022-06-07 19:50 UTC, jaanonim commented
LGTM

2022-06-07 19:56 UTC, jaanonim reviewed
Roo style

2022-06-07 19:56 UTC, jaanonim commented on static/js/Game.js
>  let zmiennaX = 4.6
missing comma

2022-06-07 19:56 UTC, jaanonim commented on static/js/Game.js
>  let zmiennaZ = 3.6
missing comma

2022-06-07 19:56 UTC, jaanonim commented on static/js/Game.js
>  let imageCounterStrike = 0
missing comma

2022-06-07 19:56 UTC, jaanonim commented on static/js/Game.js
> +let lastClickedPieceImageObj
missing comma

2022-06-07 19:56 UTC, jaanonim commented on static/js/Game.js
>                      let playerID = 3
missing comma

2022-06-07 19:56 UTC, jaanonim commented on static/js/Game.js
>                      let imageOnTopName = startImages()[imageCounterStrike]
missing comma

2022-06-07 19:56 UTC, jaanonim commented on static/js/Game.js
>                      let pieceID = imageOnTopName
missing comma

2022-06-07 19:56 UTC, jaanonim commented on static/js/Game.js
> +        if (lastClickedPieceImageObj != undefined)
missing comma

2022-06-07 19:56 UTC, jaanonim commented on static/js/Game.js
> +            console.log("ostatnio kliknięty: " + lastClickedPieceImageObj.pieceID)
missing comma

2022-06-07 19:56 UTC, jaanonim commented on static/js/Game.js
> +                    })
missing comma

2022-06-07 19:56 UTC, jaanonim commented on static/js/Game.js
> +        lastClickedPieceImageObj = intersects[0].object
missing comma

2022-06-07 19:56 UTC, jaanonim commented on static/js/Game.js
> +        console.log(lastClickedPieceImageObj)
missing comma

2022-06-07 19:56 UTC, jaanonim commented on static/js/images.js
>              imagesLeft.push(images[i].name)
missing comma

2022-06-07 19:56 UTC, jaanonim commented on static/js/images.js
>      return startingItemsArray
missing comma

2022-06-09 08:21 UTC, kdrzewiecki101 approved these changes

2022-06-09 08:21 UTC, merged